[package]
name = "parsec-client"
version = "0.9.0"
authors = ["Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "Parsec Client library for the Rust ecosystem"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec-client-rust"
readme = "README.md"
keywords = ["parsec"]
categories = ["development-tools"]
edition = "2018"
documentation = "https://docs.rs/crate/parsec-client"

[dependencies]
parsec-interface = "0.20.2"
num = "0.3.0"
log = "0.4.11"
derivative = "2.1.1"
zeroize = "1.1.0"
users = "0.10.0"
libc = "0.2.77"

[dev-dependencies]
mockstream = "0.0.3"

[features]
testing = ["parsec-interface/testing", "no-fs-permission-check"]
no-fs-permission-check = []
